version: '3'

services:

  dynamodb:
    image: lambda-stripe-api/dynamodb
    container_name: lambda-stripe-api-dynamodb
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - lambda-stripe-api-dynamodb-store:/home/dynamodblocal/data
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    networks:
      - lambda-local

  dynamodb-admin:
    container_name: lambda-stripe-api-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - lambda-local

  awscli:
    image: lambda-stripe-api/awscli
    container_name: lambda-stripe-api-awscli
    build:
      context: ./awscli
      dockerfile: Dockerfile
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    volumes:
      - ../:/aws
    working_dir: /aws
    depends_on:
      - dynamodb
    networks: 
      - lambda-local

  mailhog:
    image: mailhog/mailhog:latest
    container_name: lambda-stripe-api-mailhog
    ports:
      - 8025:8025
      - 25:1025

volumes:
  lambda-stripe-api-dynamodb-store:

networks:
  lambda-local:
    external: true